Bug 15504: (hotfix) no userid method for C4::SIP::ILS::Patron
Because of $patron->userid it dies with:

ERROR: Cannot access 'userid' field of class 'C4::SIP::ILS::Patron'
at /usr/share/koha/lib/C4/SIP/Sip/MsgType.pm line 1000.