Bug 38066: HOTFIX: Can't build .deb on 24.05.x because of:
Message:
    koha-tmpl/intranet-tmpl/prog/css/src/staff-global.scss
Error: Undefined variable.
5025 |     z-index: $zindex-tooltip;